### ISSUE TITLE
add creds

### ISSUE THREAD

**Issue by SaeedSafi1999** [quebrix/quebrix#12]
do we need creds for application?
I thing we do not need that what is your idea about this?
CC @Alirexaa  @SamanFattahiDev

**Comment by Alirexaa** [comment]
Security is important.
We should consider this.

**Comment by SaeedSafi1999** [comment]
I will adding soon as I can

**Comment by SamanFattahiDev** [comment]
I saw that authorization has been added to the application. But the question is, that the javascript and typescript client should meet any changes or it will work as before? @Alirexaa @SaeedSafi1999

**Comment by Alirexaa** [comment]
> I saw that authorization has been added to the application. But the question is, that the javascript and typescript client should meet any changes or it will work as before? @Alirexaa @SaeedSafi1999 

Yes. Those clients should use authentication token for any API call.

**Comment by SaeedSafi1999** [comment]
Yes few changes need for packages
