### ISSUE TITLE
[API Proposal] Numeric Commands

### ISSUE THREAD

**Issue by Alirexaa** [quebrix/quebrix#36]
#### Syntax
```
    INCR cluster  key 
```
Increments the number stored at key by one. If the key does not exist, it is set to 0 before performing the operation.

Resp Reply:
Integer reply: the value of the key after the increment.

#### Syntax
```
    INCRBY cluster  key increment
```
Increments the number stored at key by the value of the parameter increment. If the key does not exist, it is set to 0 before performing the operation.

Resp Reply
Integer reply: the value of the key after the increment.

#### Syntax
```
    DECR cluster key
```

Decrements the number stored at key by one. If the key does not exist, it is set to 0 before performing the operation. An error is returned if the key contains a value of the wrong type or contains a string that can not be represented as integer.

RESP Reply
Integer reply: the value of the key after decrementing it.

#### Syntax
```
    DECRBY cluster  key decrement
```
Decrements the number stored at key by the value of parameter decrement. If the key does not exist, it is set to 0 before performing the operation. An error is returned if the key contains a value of the wrong type or contains a string that can not be represented as integer.

Resp Reply
Integer reply: the value of the key after decrementing it.

**Comment by SaeedSafi1999** [comment]
in progress I will adding this to application
